<?php defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * +-----------------------------------
 * A-CDM成员机场列表
 * +-----------------------------------
 *
 * @Author: zhaobin <zhaobin@feeyo.com>
 */

$config['acdm_list'] = array(
    'KMG'   => array(
        'airport_iata'  => 'KMG',
        'airport_name'  => '昆明长水国际机场',
        'airport_runway'=> '03,21,04,22',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'BSD'  => array(
        'airport_iata'  => 'BSD',
        'airport_name'  => '保山云瑞机场',
        'airport_runway'=> '01,19',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'LJG'  => array(
        'airport_iata'  => 'LJG',
        'airport_name'  => '丽江三义机场',
        'airport_runway'=> '02,20',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'JHG'  => array(
        'airport_iata'  => 'JHG',
        'airport_name'  => '西双版纳嘎洒机场',
        'airport_runway'=> '16,34',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'LUM'  => array(
        'airport_iata'  => 'LUM',
        'airport_name'  => '芒市机场',
        'airport_runway'=> '05,23',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'TCZ'  => array(
        'airport_iata'  => 'TCZ',
        'airport_name'  => '腾冲驼峰机场',
        'airport_runway'=> '18,36',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'DIG'  => array(
        'airport_iata'  => 'DIG',
        'airport_name'  => '迪庆香格里拉机场',
        'airport_runway'=> '16,34',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'DLU'  => array(
        'airport_iata'  => 'DLU',
        'airport_name'  => '大理荒草坝机场',
        'airport_runway'=> '17,35',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'SYM'  => array(
        'airport_iata'  => 'SYM',
        'airport_name'  => '普洱思茅机场',
        'airport_runway'=> '18,36',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'LNJ'  => array(
        'airport_iata'  => 'LNJ',
        'airport_name'  => '临沧博尚机场',
        'airport_runway'=> '16,34',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'WNH'  => array(
        'airport_iata'  => 'WNH',
        'airport_name'  => '文山普者黑机场',
        'airport_runway'=> '02,20',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'ZAT'  => array(
        'airport_iata'  => 'ZAT',
        'airport_name'  => '昭通机场',
        'airport_runway'=> '04,22',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'NLH'  => array(
        'airport_iata'  => 'NLH',
        'airport_name'  => '宁蒗泸沽湖机场',
        'airport_runway'=> '05,23',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'CWJ'  => array(
        'airport_iata'  => 'CWJ',
        'airport_name'  => '沧源佤山机场',
        'airport_runway'=> '05,23',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'JMJ'  => array(
        'airport_iata'  => 'JMJ',
        'airport_name'  => '澜沧景迈机场',
        'airport_runway'=> '12,30',
        'system_prefix' => 'KMG',
        'system_name'   => '长水常准',
        'api_public_key'=> 'P.8CGq@Wr~Vs]!4!',
    ),
    'KWE'  => array(
        'airport_iata'  => 'KWE',
        'airport_name'  => '贵阳龙洞堡国际机场',
        'airport_runway'=> '01,19',
        'system_prefix' => 'KWE',
        'system_name'   => '黔程在握',
        'api_public_key'=> 'Wu~KLizo5z76LW]f',
    ),
    'AVA'  => array(
        'airport_iata'  => 'AVA',
        'airport_name'  => '安顺机场',
        'airport_runway'=> '07,25',
        'system_prefix' => 'KWE',
        'system_name'   => '黔程在握',
        'api_public_key'=> 'Wu~KLizo5z76LW]f',
    ),
    'ZYI'  => array(
        'airport_iata'  => 'ZYI',
        'airport_name'  => '遵义机场',
        'airport_runway'=> '18,36',
        'system_prefix' => 'KWE',
        'system_name'   => '黔程在握',
        'api_public_key'=> 'Wu~KLizo5z76LW]f',
    ),
    'BFJ'  => array(
        'airport_iata'  => 'BFJ',
        'airport_name'  => '毕节机场',
        'airport_runway'=> '08,26',
        'system_prefix' => 'KWE',
        'system_name'   => '黔程在握',
        'api_public_key'=> 'Wu~KLizo5z76LW]f',
    ),
    'LLB'  => array(
        'airport_iata'  => 'LLB',
        'airport_name'  => '荔波机场',
        'airport_runway'=> '03,21',
        'system_prefix' => 'KWE',
        'system_name'   => '黔程在握',
        'api_public_key'=> 'Wu~KLizo5z76LW]f',
    ),
    'ACX'  => array(
        'airport_iata'  => 'ACX',
        'airport_name'  => '兴义机场',
        'airport_runway'=> '16,34',
        'system_prefix' => 'KWE',
        'system_name'   => '黔程在握',
        'api_public_key'=> 'Wu~KLizo5z76LW]f',
    ),
    'TEN'  => array(
        'airport_iata'  => 'TEN',
        'airport_name'  => '铜仁凤凰机场',
        'airport_runway'=> '04,22',
        'system_prefix' => 'KWE',
        'system_name'   => '黔程在握',
        'api_public_key'=> 'Wu~KLizo5z76LW]f',
    ),
    'HZH'  => array(
        'airport_iata'  => 'HZH',
        'airport_name'  => '黎平机场',
        'airport_runway'=> '06,24',
        'system_prefix' => 'KWE',
        'system_name'   => '黔程在握',
        'api_public_key'=> 'Wu~KLizo5z76LW]f',
    ),
    'WUX' => array(
        'airport_iata'  => 'WUX',
        'airport_name'  => '苏南硕放国际机场',
        'airport_runway'=> '03,21',
        'system_prefix' => 'WUX',
        'system_name'   => 'WUX A-CDM',
        'api_public_key'=> 'WCoGT^6IwE!s3C8v',
    ),
    'NGB' => array(
        'airport_iata'  => 'NGB',
        'airport_name'  => '宁波栎社国际机场',
        'airport_runway'=> '13,31',
        'system_prefix' => 'NGB',
        'system_name'   => 'NGB A-CDM',
        'api_public_key'=> 'pVdWH)UJIppFv(p2',
    ),
    'TSN' => array(
        'airport_iata'  => 'TSN',
        'airport_name'  => '天津滨海国际机场',
        'airport_runway'=> '16R,34L,16L,34R',
        'system_prefix' => 'TSN',
        'system_name'   => 'TSN A-CDM',
        'api_public_key'=> '@!9,])BP!2#-#2Wj',
    ),
    'HAK' => array(
        'airport_iata'  => 'HAK',
        'airport_name'  => '海口美兰国际机场',
        'airport_runway'=> '09,27',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'SYX' => array(
        'airport_iata'  => 'SYX',
        'airport_name'  => '三亚凤凰国际机场',
        'airport_runway'=> '',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'BAR' => array(
        'airport_iata'  => 'BAR',
        'airport_name'  => '琼海博鳌国际机场',
        'airport_runway'=> '08,26',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'YIH' => array(
        'airport_iata'  => 'YIH',
        'airport_name'  => '宜昌三峡机场',
        'airport_runway'=> '14,32',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'NZH' => array(
        'airport_iata'  => 'NZH',
        'airport_name'  => '满洲里西郊机场',
        'airport_runway'=> '12,30',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'AQG' => array(
        'airport_iata'  => 'AQG',
        'airport_name'  => '安庆天柱山机场',
        'airport_runway'=> '06,24',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'WEF' => array(
        'airport_iata'  => 'WEF',
        'airport_name'  => '潍坊机场',
        'airport_runway'=> '17,35',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'YKH' => array(
        'airport_iata'  => 'YKH',
        'airport_name'  => '营口兰旗机场',
        'airport_runway'=> '',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'TVS' => array(
        'airport_iata'  => 'TVS',
        'airport_name'  => '唐山三女河机场',
        'airport_runway'=> '10,28',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'YXG' => array(
        'airport_iata'  => 'YXG',
        'airport_name'  => '南沙永暑礁机场',
        'airport_runway'=> '',
        'system_prefix' => 'HNA',
        'system_name'   => '海航机场BIM平台',
        'api_public_key'=> 'We8JrsF8Ps^of]JG',
    ),
    'PVG' => array(
        'airport_iata'  => 'PVG',
        'airport_name'  => '上海浦东国际机场',
        'airport_runway'=> '17L,35R,17R,35L,16L,34R,16R,34L',
        'system_prefix' => 'PVG',
        'system_name'   => '浦东准点',
        'api_public_key'=> 'Jt,W(~C=K(ba(eWm',
    ),
    'SHE' => array(
        'airport_iata'  => 'SHE',
        'airport_name'  => '沈阳桃仙国际机场',
        'airport_runway'=> '06,24',
        'system_prefix' => 'SHE',
        'system_name'   => 'SHE A-CDM',
        'api_public_key'=> 'KrsQl3qmKu]CMo%4',
    ),
    'CSX' => array(
        'airport_iata'  => 'CSX',
        'airport_name'  => '长沙黄花国际机场',
        'airport_runway'=> '18,36',
        'system_prefix' => 'CSX',
        'system_name'   => 'CSX A-CDM',
        'api_public_key'=> 'aa#Py-6ub~NgW%rB',
    ),
    'HUZ' => array(
        'airport_iata'  => 'HUZ',
        'airport_name'  => '惠州平潭机场',
        'airport_runway'=> '09,27',
        'system_prefix' => 'HUZ',
        'system_name'   => '惠长准',
        'api_public_key'=> 'uHMNyE-s81r-5D,x',
    ),
    'SHA' => array(
        'airport_iata'  => 'SHA',
        'airport_name'  => '上海虹桥国际机场',
        'airport_runway'=> '18L,18R,36L,36R',
        'system_prefix' => 'SHA',
        'system_name'   => '虹桥正点',
        'api_public_key'=> '%S)1F$p8M-vJLQMl',
    ),
    'NKG' => array(
        'airport_iata'  => 'NKG',
        'airport_name'  => '南京禄口国际机场',
        'airport_runway'=> '06,24,07,25',
        'system_prefix' => 'NKG',
        'system_name'   => 'NKG A-CDM',
        'api_public_key'=> '3V,377,xM,8O6~iW',
    ),
    'LHW' => array(
        'airport_iata'  => 'LHW',
        'airport_name'  => '兰州中川国际机场',
        'airport_runway'=> '18,36',
        'system_prefix' => 'LHW',
        'system_name'   => '智汇中川',
        'api_public_key'=> 'y9)K9*6AP@~d[xSv',
    ),
    'ZUH' => array(
        'airport_iata'  => 'ZUH',
        'airport_name'  => '珠海金湾国际机场',
        'airport_runway'=> '05,23',
        'system_prefix' => 'ZUH',
        'system_name'   => 'ZUH A-CDM',
        'api_public_key'=> 'q,iNbU1.=r9u7ptd',
    ),
    'YIN' => array(
        'airport_iata'  => 'YIN',
        'airport_name'  => '伊宁机场',
        'airport_runway'=> '06,24',
        'system_prefix' => 'YIN',
        'system_name'   => 'YIN A-CDM',
        'api_public_key'=> '$JSCiJwy~~z$WJUq',
    ),
    'NLT' => array(
        'airport_iata'  => 'NLT',
        'airport_name'  => '那拉提机场',
        'airport_runway'=> '08,26',
        'system_prefix' => 'NLT',
        'system_name'   => 'NLT A-CDM',
        'api_public_key'=> 'eD1MljEu9=!s+QZl',
    ),
    'SWA' => array(
        'airport_iata'  => 'SWA',
        'airport_name'  => '揭阳潮汕机场',
        'airport_runway'=> '04,22',
        'system_prefix' => 'SWA',
        'system_name'   => '潮汕常准',
        'api_public_key'=> 'UwivRBlWK%2E-z!f',
    ),
    'MIG' => array(
        'airport_iata'  => 'MIG',
        'airport_name'  => '绵阳南郊机场',
        'airport_runway'=> '14,42',
        'system_prefix' => 'MIG',
        'system_name'   => '南郊常准',
        'api_public_key'=> 'wN2O))1JXtA1E%kf',
    ),
    'HGH' => array(
        'airport_iata'  => 'HGH',
        'airport_name'  => '杭州萧山国际机场',
        'airport_runway'=> '06,07,24,25',
        'system_prefix' => 'HGH',
        'system_name'   => 'HGH A-CDM',
        'api_public_key'=> 'Ya37Ub]0G,8SW6I6',
    ),
    'URC' => array(
        'airport_iata' => 'URC',
        'airport_name' => '乌鲁木齐地窝堡机场',
        'airport_runway'=> '07,25',
        'system_prefix' => 'URC',
        'system_name'   => 'URC A-CDM',
        'api_public_key'=> 'UwivRTlWK%2E-z!D',
    ),
);